# Generated by Django 4.2.6 on 2023-10-30 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TMTool', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Toppic',
            new_name='Topic',
        ),
    ]
