# Generated by Django 4.2.7 on 2023-11-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TMTool", "0006_entry_flag_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="flag_status",
            field=models.CharField(
                choices=[
                    ("status1", "Created"),
                    ("status2", "In progress"),
                    ("status3", "Suspended"),
                    ("status4", "Done"),
                ],
                default="status1",
                max_length=15,
            ),
        ),
    ]
