# Generated by Django 4.2.7 on 2023-12-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMTool', '0007_alter_entry_flag_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='last_accessed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
