# Generated by Django 4.2.7 on 2023-12-12 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TMTool', '0009_entry_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='file',
        ),
    ]
