# Generated by Django 4.2.7 on 2023-12-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMTool', '0010_remove_entry_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='file',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
