# Generated by Django 4.2.7 on 2023-12-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMTool', '0011_entry_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='file',
            field=models.FileField(upload_to='TMTool/static/upload/'),
        ),
    ]
